# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger: none
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'Source/VideoSharing.sln'
    arguments: >
      --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'Source/VideoSharing.sln'
    arguments: >
      --configuration $(buildConfiguration)
      --no-restore

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: Test/**/*.csproj
    arguments: >
      --configuration $(buildConfiguration)
      --no-build

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: >
      --configuration $(buildConfiguration)
      --no-build
    projects: '..\VideoSharing\VideoSharing.csproj'

